---
# Create an instance for dbServer on NecTAR
- name: Create an instance for dbServer
  os_server:
    name: CouchDB_2
    image: '{{ instance_image }}'
    key_name: NectarKey
    flavor: '{{ instance_flavor }}'
    network: '{{ instance_network }}'
    availability_zone: '{{ availability_zone }}'
    security_groups: '{{ sg_names }}'
    volumes: data@CouchDB_2
    auto_floating_ip: yes
    wait: yes
    timeout: 600
    state: present
  register: os_couchdb_2

- debug:
    msg: "instance dbServer has been created. IP address is {{ os_couchdb_2.openstack.public_v4 }}"
  when: os_couchdb_2.openstack is defined


- name: Print the ip address to inventory
  shell: echo "[CouchDB_2]\n{{ os_couchdb_2.openstack.public_v4 }} ansible_ssh_private_key_file=./keys/CouchDB_2.pem\n" >> inventory/host.ini

- lineinfile:
    path: ../host_vars/instance.yaml
    line: 'couchdb_2: {{ os_couchdb_2.openstack.public_v4 }}'
    create: yes