---
# Create an instance for dbServer on NecTAR
- name: Create an instance for TweetCrawler
  os_server:
    name: TweetCrawler
    image: '{{ instance_image }}'
    key_name: NectarKey
    flavor: '{{ instance_flavor }}'
    network: '{{ instance_network }}'
    availability_zone: '{{ availability_zone }}'
    security_groups: '{{ sg_names }}'
    auto_floating_ip: yes
    wait: yes
    timeout: 600
    state: present
  register: os_instance

- debug:
    msg: "instance dbServer has been created. IP address is {{ os_instance.openstack.public_v4 }}"
  when: os_instance.openstack is defined


- name: Print the ip address to inventory
  shell: echo "[TweetCrawler]\n{{ os_instance.openstack.public_v4 }} ansible_ssh_private_key_file=./keys/NectarKey.pem\n" >> inventory/host.ini
