---
# ****************************** Common vars ******************************
availability_zone: melbourne-qh2-uom
instance_network: qh2-uom-internal
instance_flavor: uom.mse.2c9g
instance_image: 356ff1ed-5960-4ac2-96a1-0c0198e6a999

# ****************************** Security group ******************************
security_groups:
  - name: ssh
    description: "SSH access"
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0
  - name: http
    description: "HTTP"
    protocol: tcp
    port_range_min: 80
    port_range_max: 80
    remote_ip_prefix: 0.0.0.0/0
  - name: couchdb
    description: "CouchDB"
    protocol: tcp
    port_range_min: 5984
    port_range_max: 5984
    remote_ip_prefix: 0.0.0.0/0
  - name: couchdb_cluster
    description: "couchdb_cluster"
    protocol: tcp
    port_range_min: 9100 
    port_range_max: 9200
    remote_ip_prefix: 0.0.0.0/0
  - name: simple_docker
    description: "simple_docker"
    protocol: tcp
    port_range_min: 9091
    port_range_max: 9091
    remote_ip_prefix: 0.0.0.0/0


# ****************************** Volumns ******************************
volumes:
  - vol_name: data@CouchDB_1
    vol_size: 50
  - vol_name: data@CouchDB_2
    vol_size: 50
  - vol_name: data@CouchDB_3
    vol_size: 50

