FROM python:3.8

RUN mkdir /tweetcrawler

WORKDIR /tweetcrawler

COPY requirements.txt tweetHarvest.py ./

RUN pip install --no-cache-dir -r requirements.txt

ENTRYPOINT ["python", "tweetHarvest.py"]

