---
- hosts: localhost
  vars_files:
    - host_vars/mrc.yaml
  gather_facts: true

  roles:
    - role: common
    # - role: show_images
    - role: create_volumns
    - role: create_security_group
    - role: create_couchdb_1
    - role: create_couchdb_2
    - role: create_couchdb_3

