
version: '3'
services:
  redis:
    image: redis:latest
  web:
    image: registry.cn-hangzhou.aliyuncs.com/seven-tao/simple-docker:0.0.7.1
    ports:
      - "9091:4050"
    volumes:
      - /tmp/simple-docker/back:/tmp/back
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - redis
  
  couchserver:
    image: couchdb
    restart: always
    ports:
      - 5984:5984
      - 9100:9100
      - 9200:9200
      - 4369:4369
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=123456
      - ERL_FLAGS=-setcookie "brumbrum" -kernel inet_dist_listen_min 9100 -kernel inet_dist_listen_max 9200 -name couchdb
    volumes:
        - /data